# Generated by Django 5.2.7 on 2025-10-06 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='classes.campus')),
            ],
            options={
                'unique_together': {('name', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='classes.semester')),
            ],
            options={
                'unique_together': {('name', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('credits', models.IntegerField(null=True)),
                ('section', models.IntegerField(null=True)),
                ('time', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=50)),
                ('seats_taken', models.IntegerField(null=True)),
                ('seats_total', models.IntegerField(null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='classes.topics')),
            ],
            options={
                'unique_together': {('name', 'topic')},
            },
        ),
    ]
