# Generated by Django 5.2.7 on 2025-10-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
