# Generated by Django 5.2.7 on 2025-10-09 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_course_course_number_course_days_course_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classes.topics'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='classes.semester'),
        ),
    ]
