# Generated by Django 5.2.7 on 2025-10-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_course_topic_alter_topics_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
