# Generated by Django 5.2.7 on 2025-10-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_course_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seats_taken',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seats_total',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('section', models.IntegerField(null=True)),
                ('days', models.CharField(default='N/A', max_length=15)),
                ('time', models.CharField(default='N/A', max_length=15)),
                ('location', models.CharField(default='N/A', max_length=20)),
                ('instructor', models.CharField(default='N/A', max_length=50)),
                ('seats_taken', models.IntegerField(null=True)),
                ('seats_total', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes.course')),
            ],
            options={
                'unique_together': {('section', 'course')},
            },
        ),
    ]
