# Generated by Django 5.2.7 on 2025-10-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_course_code_remove_course_days_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'course_number')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('code', 'course')},
        ),
    ]
