# Generated by Django 5.2.7 on 2025-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='days',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='section',
            name='time',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
