# Generated by Django 5.2.7 on 2025-10-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_section_days_alter_section_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.CharField(default='V', max_length=1),
        ),
    ]
