# Generated by Django 5.2.7 on 2025-10-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_course_credits'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
