# Generated by Django 5.2.7 on 2025-10-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.CharField(default='V', max_length=2),
        ),
    ]
