# Generated by Codex on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_userschedule_schedulesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_required_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='component',
            field=models.CharField(default='Lecture', max_length=30),
        ),
        migrations.AddField(
            model_name='section',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
    ]
