# Generated by Codex on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_course_has_required_lab_section_lab_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='days',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='time',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
