# Generated by Codex on 2026-08-17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_expand_section_days_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=django.utils.timezone.localdate)),
                ('event_name', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date', 'event_name'],
                'unique_together': {('event_date', 'event_name')},
            },
        ),
    ]
