# Generated by Codex on 2026-08-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_dailyanalyticsmetric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAnalyticsMetric',
        ),
    ]
